### PR TITLE
(WIP) Updated spark image to spark 2.4 to bring in line with AWS Glue

### PR DESCRIPTION
**Pull request by RobinL**
For reasons unknown this currently fails with:

```
(base) ➜  analytics-platform-jupyter-notebook git:(spark_24) kubectl logs jupyter-lab-robinl-jupyt-75579f9c54-7pwrx jupyter-lab
Set username to: jovyan
usermod: no changes
Executing the command: jupyter lab --NotebookApp.token=''
sudo: jupyter lab: command not found
```

Possibly related to:
https://github.com/jupyter/docker-stacks/issues/524

### CODE REVIEW

**Comment by RobinL** [comment]
Is this the solution?
https://github.com/jupyter/docker-stacks/issues/524#issuecomment-371440373

**Comment by RobinL** [comment]
- k8s won't use the entrypoint set in the docker

- whatever is the command in the k8s deployment is what gets executed

- specifically whatever command is in the helm chart

to fix for specific spark 2.4.4 deploys:


- change tag
- change the command to start-notebook.sh rather than start.sh
- remove the line from the args which has 'jupter lab', but leave the notebook token one 

https://github.com/ministryofjustice/analytics-platform-helm-charts/tree/master/charts/jupyter-lab

**Comment by RobinL** [comment]
Specifically the things that need to change in the `yaml` are:

```
      - args:
        - --NotebookApp.token=''
        command:
        - start-notebook.sh
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "1"
        image: quay.io/mojanalytics/all-spark:spark_24
```

instead of 
```
      - args:
        - jupyter lab
        - --NotebookApp.token=''
        command:
        - start.sh
```

**Comment by damacus** [comment]
I'm going to use this as a base for a new PR. But closing for now as I need to rework the All Spark image from the ground up 👍

**Pull request closed without merging**
